platform :ios, '8.0'

target 'Pokemon Weakness' do

  use_frameworks!

  pod 'PromiseKit/CorePromise', '~> 3.2'        # A delightful Promises implementation for iOS and OS X
  pod 'SDWebImage', '~> 3.8.1'                  # Asynchronous image downloader with cache support
  
  target 'Pokemon WeaknessTests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.9'    					# The Swift (and Objective-C) testing framework
	pod 'Nimble', '~> 4.1'						# A Matcher Framework for Swift and Objective-C
  end
end
