# A list of devices you want to take the screenshots from
devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5",
  "iPhone 4s"
])

languages([
	"en-US"
	])

# The name of the scheme which contains the UI Tests
scheme "Pokemon Weakness"

# Where should the resulting screenshots be stored?
output_directory "./screenshots"

clear_previous_screenshots true

# Choose which project/workspace to use

workspace "./Pokemon Weakness.xcworkspace"
